# Generated by Django 3.0.3 on 2020-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
