# Generated by Django 3.0.3 on 2020-03-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='phone',
        ),
    ]
