# Generated by Django 3.0.3 on 2020-03-21 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0005_remove_goods_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='shops',
        ),
    ]
