# Generated by Django 3.0.3 on 2020-03-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20200321_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shops.Product')),
            ],
            options={
                'db_table': 'products_images',
            },
        ),
    ]
