# Generated by Django 3.0.3 on 2020-03-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20200321_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimages',
            name='url',
        ),
    ]
