# Generated by Django 3.0.3 on 2020-04-05 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0009_remove_productsimages_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimages',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FavoritesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='shops.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites_products',
            },
        ),
    ]
