# Generated by Django 3.0.3 on 2020-03-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200301_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='role_id',
        ),
    ]
