# Generated by Django 3.0.3 on 2020-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200301_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmed_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
