# Generated by Django 3.0.3 on 2020-03-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_confirmed_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
    ]
