# Generated by Django 3.0.3 on 2020-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200321_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
